apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
      # - {key: app, operator: In, values: [second-app, first-app]}
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: vrigzalejo/kub-first-app:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5