apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: vrigzalejo/kub-data-demo
    
