apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: vrigzalejo/kub-dep-tasks:latest
          envFrom:
          - configMapRef:
              name: deploy-config
